add_executable(semilive_publisher_timing_test
    publisher_timing_test.cpp
)
target_link_libraries(semilive_publisher_timing_test PRIVATE
    semilive_publisher_core
)
semilive_enable_warnings(semilive_publisher_timing_test)

add_test(NAME semilive_publisher_timing COMMAND semilive_publisher_timing_test)
